version: '3.8'

services:
  api:
    build: .
    container_name: peakform-api
    ports:
      - "3000:3000"
    volumes:
      - ./assets/exercises:/root/assets/exercises
      - ./public/profile:/root/public/profile
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - peakform-net

  db:
    image: postgres:15
    container_name: peakform-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: api_peak_form
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - peakform-net

volumes:
  pgdata:

networks:
  peakform-net:
