package datadumy

import (
	"api-peak-form/domain"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

func AddExercise(db *gorm.DB) {
	// Data dummy untuk tabel Exercise
	exercises := []domain.Exercise{
		{
			ID:           125,
			Name:         "Pushups",
			Type:         "strength",
			Muscle:       "chest",
			Equipment:    "body_only",
			Difficulty:   "intermediate",
			Instructions: "Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length. Next, lower yourself downward until your chest almost touches the floor as you inhale. Now breathe out and press your upper body back up to the starting position while squeezing your chest. After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed. Variations: If you are new at this exercise and do not have the strength to perform it, you can either bend your legs at the knees to take off resistance or perform the exercise against the wall instead of the floor. For the most advanced lifters, you can place your feet at a high surface such as a bench in order to increase the resistance and to target the upper chest more.",
			Image:        "pushup.svg",
		},
		{
			ID:           126,
			Name:         "Palms-Up Dumbbell Wrist Curl Over A Bench",
			Type:         "strength",
			Muscle:       "forearms",
			Equipment:    "dumbbell",
			Difficulty:   "beginner",
			Instructions: "Start out by placing two dumbbells on one side of a flat bench. Kneel down on both of your knees so that your body is facing the flat bench. Use your arms to grab both of the dumbbells with a supinated grip (palms up) and bring them up so that your forearms are resting against the flat bench. Your wrists should be hanging over the edge. Start out by curling your wrist upwards and exhaling. Slowly lower your wrists back down to the starting position while inhaling. Make sure to inhale during this part of the exercise. Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.",
			Image:        "wristcurlup.svg",
		},
		{
			ID:           127,
			Name:         "Palms-Down Dumbbell Wrist Curl Over A Bench",
			Type:         "strength",
			Muscle:       "forearms",
			Equipment:    "dumbbell",
			Difficulty:   "beginner",
			Instructions: "Start out by placing two dumbbells on one side of a flat bench. Kneel down on both of your knees so that your body is facing the flat bench. Use your arms to grab both of the dumbbells with a pronated grip (palms facing down) and bring them up so that your forearms are resting against the flat bench. Your wrists should be hanging over the edge. Start out by curling your wrist upwards and exhaling. Slowly lower your wrists back down to the starting position while inhaling.",
			Image:        "wristcurldown.svg",
		},
		{
			ID:           128,
			Name:         "Dumbbell Suitcase Carry",
			Type:         "strength",
			Muscle:       "forearms",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Place a dumbbell on the floor in front of you, making sure you have enough open space to walk. Squat down keeping your back flat and grasp the weight with a neutral grip. Keep your body square as much as possible. Stand back up by extending at the hips and knees; this will be your starting position. Keeping the weight at your side, walk forward as far as you can. Descend into a squat to lower the weight back to the floor.",
			Image:        "suitcasecarry.svg",
		},
		{
			ID:           129,
			Name:         "Pull-up",
			Type:         "strength",
			Muscle:       "lats",
			Equipment:    "body_only",
			Difficulty:   "beginner",
			Instructions: "Take a wide grip on a pull-up bar, hanging freely with your arms extended. This will be your starting position. Pull yourself up by flexing the elbows and adducting the glenohumeral joint. Attempt to get your chin above your hands. Pause at the top of the motion before lowering yourself to the starting position.",
			Image:        "pullup.svg",
		},
		{
			ID:           130,
			Name:         "Wide-Grip Rear Pull-Up",
			Type:         "strength",
			Muscle:       "lats",
			Equipment:    "body_only",
			Difficulty:   "beginner",
			Instructions: "Grab the pull-up bar with the palms facing forward using a wide grip. Bring your torso forward and head so that there is an imaginary line from the pull-up bar to the back of your neck. Pull your torso up until the bar is near the back of your neck. Concentrate on squeezing the back muscles once you reach the full contracted position. Slowly lower your torso back to the starting position.",
			Image:        "widepullup.svg",
		},
		{
			ID:           131,
			Name:         "Muscle Up",
			Type:         "strength",
			Muscle:       "lats",
			Equipment:    "body_only",
			Difficulty:   "intermediate",
			Instructions: "Grip the rings using a false grip, with the base of your palms on top of the rings. Initiate a pull up by pulling the elbows down to your side. As you reach the top position of the pull-up, pull the rings to your armpits. This puts you into the proper position to continue into the dip portion of the movement. Maintaining control and stability, extend through the elbow to complete the motion.",
			Image:        "muscleup.svg",
		},
		{
			ID:           132,
			Name:         "Rope Climb",
			Type:         "strength",
			Muscle:       "lats",
			Equipment:    "body_only",
			Difficulty:   "intermediate",
			Instructions: "Grab the rope with both hands above your head. Pull down on the rope as you take a small jump. Wrap the rope around one leg, using your feet to pinch the rope. Reach up as high as possible with your arms, gripping the rope tightly. Release the rope from your feet as you pull yourself up with your arms. Continue until you reach the top of the rope. To lower yourself, loosen the grip of your feet on the rope as you slide down using a hand over hand motion.",
			Image:        "ropeclimb.svg",
		},
		{
			ID:           133,
			Name:         "Hyperextensions With No Hyperextension Bench",
			Type:         "strength",
			Muscle:       "lower_back",
			Equipment:    "body_only",
			Difficulty:   "beginner",
			Instructions: "With someone holding down your legs, slide yourself down to the edge of a flat bench until your hips hang off the end of the bench. Tip: Your entire upper body should be hanging down towards the floor. Also, you will be in the same position as if you were on a hyperextension bench but the range of motion will be shorter due to the height of the flat bench vs. that of the hyperextension bench. With your body straight, cross your arms in front of you (my preference) or behind your head. This will be your starting position. Tip: You can also hold a weight plate for extra resistance in front of you under your crossed arms. Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you almost touch the floor or you feel a nice stretch on the hamstrings (whichever comes first). Tip: Never round the back as you perform this exercise. Slowly raise your torso back to the initial position as you exhale. Tip: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury. Repeat for the recommended amount of repetitions. Variations: This exercise can also be performed using a hyperextension bench. Also, a similar exercise to this one is the good morning and the stiff-legged deadlift.",
			Image:        "lowerbackhyperextension.svg",
		},
		{
			ID:           134,
			Name:         "Dumbbell Fix Dumbbell Deadlift",
			Type:         "strength",
			Muscle:       "lower_back",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "",
			Image:        "deadlift.svg",
		},
		{
			ID:           135,
			Name:         "Back extension",
			Type:         "strength",
			Muscle:       "lower_back",
			Equipment:    "body_only",
			Difficulty:   "intermediate",
			Instructions: "Lie face down on a hyperextension bench, tucking your ankles securely under the footpads. Adjust the upper pad if possible so your upper thighs lie flat across the wide pad, leaving enough room for you to bend at the waist without any restriction. With your body straight, cross your arms in front of you (my preference) or behind your head. This will be your starting position. Tip: You can also hold a weight plate for extra resistance in front of you under your crossed arms. Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you feel a nice stretch on the hamstrings and you can no longer keep going without a rounding of the back. Tip: Never round the back as you perform this exercise. Also, some people can go farther than others. The key thing is that you go as far as your body allows you to without rounding the back. Slowly raise your torso back to the initial position as you inhale. Tip: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury. Repeat for the recommended amount of repetitions. Variations: This exercise can also be performed without a hyperextension bench, but in this case, you will need a spotter. Also, a similar exercise to this one is the good morning and the stiff-legged deadlift.",
			Image:        "backextension.svg",
		},
		{
			ID:           136,
			Name:         "Bent Over Two-Dumbbell Row With Palms In",
			Type:         "strength",
			Muscle:       "middle_back",
			Equipment:    "dumbbell",
			Difficulty:   "beginner",
			Instructions: "With a dumbbell in each hand (palms facing each other), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The weights should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position. While keeping the torso stationary, lift the dumbbells to your side as you breathe out, squeezing your shoulder blades together. On the top contracted position, squeeze the back muscles and hold for a second. Slowly lower the weight again to the starting position as you inhale. Repeat for the recommended amount of repetitions.",
			Image:        "bentoverrow.svg",
		},
		{
			ID:           137,
			Name:         "One-Arm Dumbbell Row",
			Type:         "strength",
			Muscle:       "middle_back",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Choose a flat bench and place a dumbbell on each side of it. Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support. Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position. Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step.",
			Image:        "dumbellrow.svg",
		},
		{
			ID:           138,
			Name:         "Isometric Neck Exercise - Sides",
			Type:         "strength",
			Muscle:       "neck",
			Equipment:    "body_only",
			Difficulty:   "beginner",
			Instructions: "With your head and neck in a neutral position (normal position with head erect facing forward), place your left hand on the left side of your head. Now gently push towards the left as you contract the left neck muscles but resisting any movement of your head. Start with slow tension and increase slowly. Keep breathing normally as you execute this contraction. Hold for the recommended number of seconds.",
			Image:        "necksides.svg",
		},
		{
			ID:           139,
			Name:         "Dumbbell Goblet Squat",
			Type:         "strength",
			Muscle:       "quadriceps",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "From a standing position cradle the head of a dumbbell close to your chest with both hands. You should be looking straight forward, with your shoulders back, your spine straight, and your feet just outside of shoulder width. This will be your starting position. Initiate the movement by descending into a squat, flexing the hips and knees to lower your body.",
			Image:        "gobletsquat.svg",
		},
		{
			ID:           140,
			Name:         "Dumbbell squat",
			Type:         "strength",
			Muscle:       "quadriceps",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Stand up straight while holding a dumbbell on each hand (palms facing the side of your legs). Position your legs using a shoulder-width medium stance with the toes slightly pointed out. Keep your head up at all times.",
			Image:        "dumbellsquat.svg",
		},
		{
			ID:           141,
			Name:         "Forward lunge",
			Type:         "strength",
			Muscle:       "quadriceps",
			Equipment:    "body_only",
			Difficulty:   "intermediate",
			Instructions: "Stand erect with your feet hip-width apart, chest out, and shoulders back, maintaining the natural curvature of your spine. Your knees should be unlocked and your hand on your hips. This is your starting position.",
			Image:        "lunge.svg",
		},

		{
			ID:           142,
			Name:         "Standing dumbbell shrug",
			Type:         "strength",
			Muscle:       "traps",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Stand erect with a dumbbell on each hand (palms facing your torso), arms extended on the sides. Lift the dumbbells by elevating the shoulders as high as possible while you exhale. Hold the contraction at the top for a second. Tip: The arms should remain extended at all times. Refrain from using the biceps to help lift the dumbbells. Only the shoulders should be moving up and down. Lower the dumbbells back to the original position. Repeat for the recommended amount of repetitions. Variations: You can perform this exercise with bands, barbells or cables. You can also use a single handle and work one side at a time.",
			Image:        "shrug.svg",
		},
		{
			ID:           143,
			Name:         "Standing dumbbell upright row",
			Type:         "strength",
			Muscle:       "traps",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Grasp a dumbbell in each hand with a pronated (palms forward) grip that is slightly less than shoulder width. The dumbbells should be resting on top of your thighs. Your arms should be extended with a slight bend at the elbows and your back should be straight. This will be your starting position. Use your side shoulders to lift the dumbbells as you exhale. The dumbbells should be close to the body as you move it up and the elbows should drive the motion. Continue to lift them until they nearly touch your chin. Tip: Your elbows should drive the motion. As you lift the dumbbells, your elbows should always be higher than your forearms. Also, keep your torso stationary and pause for a second at the top of the movement. Lower the dumbbells back down slowly to the starting position. Inhale as you perform this portion of the movement. Repeat for the recommended amount of repetitions. Caution: Be very careful with how much weight you use in this exercise. Too much weight leads to bad form, which in turn can cause shoulder injury. I've seen this too many times so please no jerking, swinging and cheating. Also, if you suffer from shoulder problems, you may want to stay away from upright rows and substitute by some form of lateral raises. Variations: This exercise can also be performed using a straight bar attached to a low pulley and it can also be performed using an e-z bar.",
			Image:        "uprightrow.svg",
		},
		{
			ID:           144,
			Name:         "One Arm Supinated Dumbbell Triceps Extension",
			Type:         "strength",
			Muscle:       "triceps",
			Equipment:    "dumbbell",
			Difficulty:   "beginner",
			Instructions: "Lie flat on a bench while holding a dumbbell at arms length. Your arm should be perpendicular to your body. The palm of your hand should be facing towards your face as a supinated grip is required to perform this exercise. Place your non lifting hand on your bicep for support. Slowly begin to lower the dumbbell down as you breathe in. Then, begin lifting the dumbbell upward as you contract the triceps. Remember to breathe out during the concentric (lifting part of the exercise). Repeat until you have performed your set repetitions. Switch arms and repeat the movement. Switch arms again and repeat the movement. Caution: When you are done, do not drop the dumbbell next to you as this is dangerous to your rotator cuff in your shoulders and others working out around you. Just lift your legs from the floor bending at the knees, twist your wrist so that you can place the dumbbell on top of your thigh. When the dumbbell is touching your thigh simultaneously push your upper torso up (while pressing the dumbbell on your thigh) and also perform a slight kick forward with your legs (keeping the dumbbell on top of the thigh). By doing this combined movement, momentum will help you get back to a sitting position with the dumbbell still on top of your thigh. At this moment you can place the dumbbell on the floor.",
			Image:        "tricepsextension.svg",
		},
		{
			ID:           145,
			Name:         "Seated Bent-Over Two-Arm Dumbbell Triceps Extension",
			Type:         "strength",
			Muscle:       "triceps",
			Equipment:    "dumbbell",
			Difficulty:   "beginner",
			Instructions: "Sit down at the end of a flat bench with a dumbbell in both arms using a neutral grip (palms of the hand facing you). Bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Make sure that you keep the head up. The upper arms with the dumbbells should be close to the torso and aligned with it (lifted up until they are parallel to the floor while the forearms are pointing towards the floor as the hands hold the weights). Tip: There should be a 90-degree angle between the forearms and the upper arm. This is your starting position. Keeping the upper arms stationary, use the triceps to lift the weight as you exhale until the forearms are parallel to the floor and the whole arm is extended. Like many other arm exercises, only the forearm moves. After a second contraction at the top, slowly lower the dumbbells back to the starting position as you inhale. Repeat the movement for the prescribed amount of repetitions. Variation: This exercise can be executed also one arm at a time or alternating (like alternating dumbbell curls)",
			Image:        "dumbellrowtricep.svg",
		},
		{
			ID:           146,
			Name:         "Triceps dip",
			Type:         "strength",
			Muscle:       "triceps",
			Equipment:    "body_only",
			Difficulty:   "intermediate",
			Instructions: "To get into the starting position, hold your body at arm's length with your arms nearly locked above the bars. Now, inhale and slowly lower yourself downward. Your torso should remain upright and your elbows should stay close to your body. This helps to better focus on tricep involvement. Lower yourself until there is a 90 degree angle formed between the upper arm and forearm. Then, exhale and push your torso back up using your triceps to bring your body back to the starting position. Repeat the movement for the prescribed amount of repetitions. Variations: If you are new at this exercise and do not have the strength to perform it, use a dip assist machine if available. These machines use weight to help you push your bodyweight. Otherwise, a spotter holding your legs can help. More advanced lifters can add weight to the exercise by using a weight belt that allows the addition of weighted plates.",
			Image:        "dip.svg",
		},
		{
			ID:           147,
			Name:         "Push-Ups - Close Triceps Position",
			Type:         "strength",
			Muscle:       "triceps",
			Equipment:    "body_only",
			Difficulty:   "intermediate",
			Instructions: "Lie on the floor face down and place your hands closer than shoulder width for a close hand position. Make sure that you are holding your torso up at arms' length. Lower yourself until your chest almost touches the floor as you inhale. Using your triceps and some of your pectoral muscles, press your upper body back up to the starting position and squeeze your chest. Breathe out as you perform this step. After a second pause at the contracted position, repeat the movement for the prescribed amount of repetitions. Variations: If you are new at this exercise and do not have the strength to perform it, you can either bend your legs at the knees to take off resistance or perform the exercise against the wall instead of the floor. For the most advanced lifters, you can place your feet at a high surface such as a bench in order to increase the resistance.",
			Image:        "closepushup.svg",
		},
		{
			ID:           148,
			Name:         "Vertical Mountain Climber",
			Type:         "cardio",
			Muscle:       "quadriceps",
			Equipment:    "body_only",
			Difficulty:   "beginner",
			Instructions: "From a standing position, raise your left hand reaching as high as you can, while driving your right knee up in a similar movement to a traditional mountain climber. Switch by pulling down with your left hand and reaching high with your right hand. At the same time, let your right foot fall to the floor, then drive with your left knee up. Repeat for the recommended amount of repetitions.",
			Image:        "vertical-mountain-climber.svg",
		},
		{
			ID:           149,
			Name:         "Slow Jog",
			Type:         "cardio",
			Muscle:       "quadriceps",
			Equipment:    "body_only",
			Difficulty:   "beginner",
			Instructions: "Begin standing with your feet shoulder-width apart. Your arms should be bent and at your sides. Lift your right knee up until it reaches your waist. Your left arm should swing forward while your right arm swings back. Keep your left knee slightly bent and allow it to spring. Return your right foot to the ground as you lift your left knee. Swing your right arm forward and your left arm back. Keep your right knee slightly bent and allow it to spring. Repeat.",
			Image:        "slow-jog.svg",
		},
		{
			ID:           150,
			Name:         "Jumping Rope",
			Type:         "cardio",
			Muscle:       "quadriceps",
			Equipment:    "body_only",
			Difficulty:   "intermediate",
			Instructions: "Hold an end of the rope in each hand. Position the rope behind you on the ground. Raise your arms up and turn the rope over your head bringing it down in front of you. When it reaches the ground, jump over it. Find a good turning pace that can be maintained. Different speeds and techniques can be used to introduce variation.",
			Image:        "jumping-rope.svg",
		},
		{
			ID:           151,
			Name:         "Burpee",
			Type:         "cardio",
			Muscle:       "quadriceps",
			Equipment:    "body_only",
			Difficulty:   "intermediate",
			Instructions: "Begin standing with your legs shoulder-width apart. Place your hands on the floor and kick your legs back so you end up with your stomach and thighs on the floor. Your elbows should be bent. From this position, press up like you're doing a push-up and push your hips up. Jump your feet under your hips and stand. Finish the movement by jumping in the air and bringing your hands over your head. Repeat.",
			Image:        "burpee.svg",
		},
		{
			ID:           152,
			Name:         "Trail Running/Walking",
			Type:         "cardio",
			Muscle:       "quadriceps",
			Equipment:    "body_only",
			Difficulty:   "intermediate",
			Instructions: "Running or hiking on trails will get the blood pumping and heart beating almost immediately. Make sure you have good shoes. Take smaller steps as you walk downhill, keep your knees bent to reduce the impact and slow down to avoid falling.",
			Image:        "trail-running-walking.svg",
		},
		{
			ID:           153,
			Name:         "Crunch - Hands Overhead",
			Type:         "strength",
			Muscle:       "abdominals",
			Equipment:    "body_only",
			Difficulty:   "beginner",
			Instructions: "Lie on the floor with your back flat and knees bent. Keep your feet flat on the floor and stretch your arms overhead. Curl your upper body forward and bring your shoulder blades just off the floor. Keep your arms aligned with your head, neck, and shoulder. Slowly lower down to the starting position. Repeat for the recommended amount of repetitions.",
			Image:        "crunch-hands-overhead.svg",
		},
		{
			ID:           154,
			Name:         "Elbow Plank",
			Type:         "strength",
			Muscle:       "abdominals",
			Equipment:    "body_only",
			Difficulty:   "intermediate",
			Instructions: "Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder. Keep your body straight at all times, and hold this position as long as possible.",
			Image:        "elbow-plank.svg",
		},
		{
			ID:           155,
			Name:         "Spider Crawl",
			Type:         "strength",
			Muscle:       "abdominals",
			Equipment:    "body_only",
			Difficulty:   "intermediate",
			Instructions: "Begin in a prone position on the floor. Support your weight on your hands and toes, with your feet together and your body straight. Raise one foot off the ground, externally rotate the leg, and bring the knee toward your elbow. Return to the starting position and repeat on the opposite side.",
			Image:        "spider-crawl.svg",
		},
		{
			ID:           156,
			Name:         "Incline Hammer Curls",
			Type:         "strength",
			Muscle:       "biceps",
			Equipment:    "dumbbell",
			Difficulty:   "beginner",
			Instructions: "Seat yourself on an incline bench with a dumbbell in each hand. Keep your back pressed firmly against the bench. Initiate the movement by flexing at the elbow, keeping the upper arm stationary. Continue to the top of the movement and pause, then slowly return to the start position.",
			Image:        "incline-hammer-curls.svg",
		},
		{
			ID:           157,
			Name:         "Biceps Curl to Shoulder Press",
			Type:         "strength",
			Muscle:       "biceps",
			Equipment:    "dumbbell",
			Difficulty:   "beginner",
			Instructions: "Begin in a standing position with a dumbbell in each hand. Curl the weight up, then press above your head. Pause at the top before reversing the movement to return to the starting position.",
			Image:        "biceps-curl-to-shoulder-press.svg",
		},
		{
			ID:           158,
			Name:         "Flexor Incline Dumbbell Curls",
			Type:         "strength",
			Muscle:       "biceps",
			Equipment:    "dumbbell",
			Difficulty:   "beginner",
			Instructions: "Hold the dumbbell towards the side farther from you. Perform a normal incline dumbbell curl, keeping your wrists as far back as possible. Sit on an incline bench at a 45-degree angle while holding a dumbbell in each hand. Curl up the two dumbbells at the same time until your biceps are fully contracted. Lower down slowly to avoid injury.",
			Image:        "flexor-incline-dumbbell-curls.svg",
		},
		{
			ID:           159,
			Name:         "Hammer Curls",
			Type:         "strength",
			Muscle:       "biceps",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Stand up with your torso upright and a dumbbell on each hand being held at arms length. The elbows should be close to the torso. The palms of the hands should be facing your torso. This will be your starting position. Now, while holding your upper arm stationary, exhale and curl the weight forward while contracting the biceps. Continue to raise the weight until the biceps are fully contracted and the dumbbell is at shoulder level. Hold the contracted position for a brief moment as you squeeze the biceps. Tip: Focus on keeping the elbow stationary and only moving your forearm. After the brief pause, inhale and slowly begin the lower the dumbbells back down to the starting position. Repeat for the recommended amount of repetitions.  Variations: There are many possible variations for this movement. For instance, you can perform the exercise sitting down on a bench with or without back support and you can also perform it by alternating arms; first lift the right arm for one repetition, then the left, then the right, etc.",
			Image:        "hammer-curls.svg",
		},
		{
			ID:           160,
			Name:         "Concentration curl",
			Type:         "strength",
			Muscle:       "biceps",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Sit down on a flat bench with one dumbbell in front of you between your legs. Your legs should be spread with your knees bent and feet on the floor. Use your right arm to pick the dumbbell up. Place the back of your right upper arm on the top of your inner right thigh. Rotate the palm of your hand until it is facing forward away from your thigh. Tip: Your arm should be extended and the dumbbell should be above the floor. This will be your starting position. While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Tip: At the top of the movement make sure that the little finger of your arm is higher than your thumb. This guarantees a good contraction. Hold the contracted position for a second as you squeeze the biceps. Slowly begin to bring the dumbbells back to starting position as your breathe in. Caution: Avoid swinging motions at any time. Repeat for the recommended amount of repetitions. Then repeat the movement with the left arm.  Variations: This exercise can be performed standing with the torso bent forward and the arm in front of you. In this case, no leg support is used for the back of your arm so you will need to make extra effort to ensure no movement of the upper arm. This is a more challenging version of the exercise and is not recommended for people with lower back issues.",
			Image:        "concentration-curl.svg",
		},
		{
			ID:           161,
			Name:         "Dumbbell Bicep Curl",
			Type:         "strength",
			Muscle:       "biceps",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Stand up straight with a dumbbell in each hand at arm's length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position. Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps. Then, inhale and slowly begin to lower the dumbbells back to the starting position. Repeat for the recommended amount of repetitions.  Variations: There are many possible variations for this movement. For instance, you can perform the exercise sitting down on a bench with or without back support and you can also perform it by alternating arms; first lift the right arm for one repetition, then the left, then the right, etc. You can also do the exercise starting with both palms of the hands facing the torso and then rotating forward as the movement is performed. At the top of the movement the palms should face forward and the small finger should be higher than the thumb for a peak contraction.",
			Image:        "dumbbell-bicep-curl.svg",
		},
		{
			ID:           162,
			Name:         "Calf Raise On A Dumbbell",
			Type:         "strength",
			Muscle:       "calves",
			Equipment:    "dumbbell",
			Difficulty:   "beginner",
			Instructions: "Hang on to a sturdy object for balance and stand on a dumbbell handle, preferably one with round plates so that it rolls as in this manner you have to work harder to stabilize yourself; thus increasing the effectiveness of the exercise. Now roll your foot slightly forward so that you can get a nice stretch of the calf. This will be your starting position. Lift the calf as you roll your foot over the top of the handle so that you get a full extension. Exhale during the execution of this movement. Contract the calf hard at the top and hold for a second. Tip: As you come up, roll the dumbbell slightly backward. Now inhale as you roll the dumbbell slightly forward as you come down to get a better stretch. Repeat for the recommended amount of repetitions.  Variations: You can also do these standing on the head of the dumbbell, using a large dumbbell that is wider.",
			Image:        "calf-raise-on-a-dumbbell.svg",
		},
		{
			ID:           163,
			Name:         "Dumbbell Seated One-Leg Calf Raise",
			Type:         "strength",
			Muscle:       "calves",
			Equipment:    "dumbbell",
			Difficulty:   "beginner",
			Instructions: "Place a block on the floor about 12 inches from a flat bench. Sit on a flat bench and place a dumbbell on your upper left thigh about 3 inches above your knee. Now place the ball of your left foot on the block. This will be your starting position. Raise your toes up as high as possible as you exhale and you contract your calf muscle. Hold the contraction for a second. Slowly return to the starting position, stretching as far down as possible. Repeat for your prescribed number of repetitions and then repeat with the right leg.  Variations: You can perform this exercise also with both legs at the same time as well as using a seated calf raise machine.",
			Image:        "dumbbell-seated-one-leg-calf-raise.svg",
		},
		{
			ID:           164,
			Name:         "Standing Dumbbell Calf Raise",
			Type:         "strength",
			Muscle:       "calves",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Stand with your torso upright holding two dumbbells in your hands by your sides. Place the ball of the foot on a sturdy and stable wooden board (that is around 2-3 inches tall) while your heels extend off and touch the floor. This will be your starting position. With the toes pointing either straight (to hit all parts equally), inwards (for emphasis on the outer head) or outwards (for emphasis on the inner head), raise the heels off the floor as you exhale by contracting the calves. Hold the top contraction for a second. As you inhale, go back to the starting position by slowly lowering the heels. Repeat for the recommended amount of times.  Note: As you become stronger you may need to use wrist wraps to avoid having the dumbbells slip out of your hands.",
			Image:        "standing-dumbbell-calf-raise.svg",
		},
		{
			ID:           165,
			Name:         "Reverse-grip incline dumbbell bench press",
			Type:         "strength",
			Muscle:       "chest",
			Equipment:    "dumbbell",
			Difficulty:   "beginner",
			Instructions: "Lay on an incline bench holding a dumbbell in each hand. Begin with your arms extended above your torso with a supinated grip. Your back should be arched, feet driving through the ground, and lats tight. This will be your starting position. Lower the weights to your chest by flexing the elbows. After a brief pause, return the weights to the starting position by extending the elbows",
			Image:        "reverse-grip-incline-dumbbell-bench-press.svg",
		},
		{
			ID:           166,
			Name:         "Hands-elevated push-up",
			Type:         "strength",
			Muscle:       "chest",
			Equipment:    "body_only",
			Difficulty:   "beginner",
			Instructions: "Stand facing a Smith machine bar or sturdy elevated platform at an appropriate height. Place your hands on the bar, with your hands about shoulder width apart. Position your feet back from the bar with arms and body straight. This will be your starting position. Keeping your body straight, lower your chest to the bar by bending the arms. Return to the starting position by extending the elbows, pressing yourself back up.",
			Image:        "hands-elevated-push-up.svg",
		},
		{
			ID:           167,
			Name:         "Dumbbell Bench Press",
			Type:         "strength",
			Muscle:       "chest",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Lie down on a flat bench with a dumbbell in each hand resting on top of your thighs. The palms of your hands will be facing each other. Then, using your thighs to help raise the dumbbells up, lift the dumbbells one at a time so that you can hold them in front of you at shoulder width. Once at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. The dumbbells should be just to the sides of your chest, with your upper arm and forearm creating a 90 degree angle. Be sure to maintain full control of the dumbbells at all times. This will be your starting position. Then, as you breathe out, use your chest to push the dumbbells up. Lock your arms at the top of the lift and squeeze your chest, hold for a second and then begin coming down slowly. Tip: Ideally, lowering the weight should take about twice as long as raising it. Repeat the movement for the prescribed amount of repetitions of your training program.  Caution: When you are done, do not drop the dumbbells next to you as this is dangerous to your rotator cuff in your shoulders and others working out around you. Just lift your legs from the floor bending at the knees, twist your wrists so that the palms of your hands are facing each other and place the dumbbells on top of your thighs. When both dumbbells are touching your thighs simultaneously push your upper torso up (while pressing the dumbbells on your thighs) and also perform a slight kick forward with your legs (keeping the dumbbells on top of the thighs). By doing this combined movement, momentum will help you get back to a sitting position with both dumbbells still on top of your thighs. At this moment you can place the dumbbells on the floor. Variations: Another variation of this exercise is to perform it with the palms of the hands facing each other. Also, you can perform the exercise with the palms facing each other and then twisting the wrist as you lift the dumbbells so that at the top of the movement the palms are facing away from the body. I personally do not use this variation very often as it seems to be hard on my shoulders.",
			Image:        "dumbbell-bench-press.svg",
		},
		{
			ID:           168,
			Name:         "Dumbbell Flyes",
			Type:         "strength",
			Muscle:       "chest",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Lie down on a flat bench with a dumbbell on each hand resting on top of your thighs. The palms of your hand will be facing each other. Then using your thighs to help raise the dumbbells, lift the dumbbells one at a time so you can hold them in front of you at shoulder width with the palms of your hands facing each other. Raise the dumbbells up like you're pressing them, but stop and hold just before you lock out. This will be your starting position. With a slight bend on your elbows in order to prevent stress at the biceps tendon, lower your arms out at both sides in a wide arc until you feel a stretch on your chest. Breathe in as you perform this portion of the movement. Tip: Keep in mind that throughout the movement, the arms should remain stationary; the movement should only occur at the shoulder joint. Return your arms back to the starting position as you squeeze your chest muscles and breathe out. Tip: Make sure to use the same arc of motion used to lower the weights. Hold for a second at the contracted position and repeat the movement for the prescribed amount of repetitions.  Variations: You may want to use a palms facing forward version for different stimulation.",
			Image:        "dumbbell-flyes.svg",
		},
		{
			ID:           169,
			Name:         "Incline dumbbell bench press",
			Type:         "strength",
			Muscle:       "chest",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Lie back on an incline bench with a dumbbell in each hand atop your thighs. The palms of your hands will be facing each other. Then, using your thighs to help push the dumbbells up, lift the dumbbells one at a time so that you can hold them at shoulder width. Once you have the dumbbells raised to shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position. Be sure to keep full control of the dumbbells at all times. Then breathe out and push the dumbbells up with your chest. Lock your arms at the top, hold for a second, and then start slowly lowering the weight. Tip Ideally, lowering the weights should take about twice as long as raising them. Repeat the movement for the prescribed amount of repetitions. When you are done, place the dumbbells back on your thighs and then on the floor. This is the safest manner to release the dumbbells.  Variations: You can use several angles on the incline bench if the bench you are using is adjustable. Another variation of this exercise is to perform it with the palms of the hands facing each other. Also, you can perform the exercise with the palms facing each other and then twisting the wrist as you lift the dumbbells so that at the top of the movement the palms are facing away from the body. I personally do not use this variation very often as it seems to be hard on my shoulders.",
			Image:        "grip-incline-dumbbell-bench-press.svg",
		},
		{
			ID:           170,
			Name:         "Single-arm palm-in dumbbell shoulder press",
			Type:         "strength",
			Muscle:       "shoulders",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Start by having a dumbbell in one hand with your arm fully extended to the side using a neutral grip. Use your other arm to hold on to an incline bench to keep your balance. Your feet should be shoulder width apart from each other. Now slowly lift the dumbbell up until you create a 90 degree angle with your arm. Note: Your forearm should be perpendicular to the floor. Continue to maintain a neutral grip throughout the entire exercise. Slowly lift the dumbbell up until your arm is fully extended. This the starting position. While inhaling lower the weight down until your arm is at a 90 degree angle again. Feel the contraction for a second and then lift the weight back up towards the starting position while exhaling. Remember to hold on to the incline bench and keep your feet positioned to keep balance during the exercise. Repeat for the recommended amount of repetitions. Switch arms and repeat the exercise.  Variation: This exercise can be performed with dumbbells in each arm as the dumbbells will help to keep you balanced. This is another great way to add variety to your routines and keep them interesting.",
			Image:        "shoulder-press.svg",
		},
		{
			ID:           171,
			Name:         "Single-arm lateral raise",
			Type:         "strength",
			Muscle:       "shoulders",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Pick a dumbbell and place it in one of your hands. Your non lifting hand should be used to grab something steady such as an incline bench press. Lean towards your lifting arm and away from the hand that is gripping the incline bench as this will allow you to keep your balance. Stand with a straight torso and have the dumbbell by your side at arm’s length with the palm of the hand facing you. This will be your starting position. While maintaining the torso stationary (no swinging), lift the dumbbell to your side with a slight bend on the elbow and your hand slightly tilted forward as if pouring water in a glass. Continue to go up until you arm is parallel to the floor. Exhale as you execute this movement and pause for a second at the top. Lower the dumbbell back down slowly to the starting position as you inhale. Repeat for the recommended amount of repetitions. Switch arms and repeat the exercise.  Variations: This exercise can also be performed sitting down.",
			Image:        "lateral-raise.svg",
		},
		{
			ID:           172,
			Name:         "Overhead dumbbell front raise",
			Type:         "strength",
			Muscle:       "shoulders",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "Hold the dumbbells in front of your thighs, palms facing your thighs. Keep your arms straight with a slight bend at the elbows but keep them locked. This will be your starting position. Raise the dumbbells in a semicircular motion to arm's length overhead as you exhale. Slowly return to the starting position using the same path as you inhale. Repeat for the recommended amount of repetitions.  Variation: You can perform this exercise with a barbell or by alternating dumbbells.",
			Image:        "front-raise.svg",
		},
		{
			ID:           173,
			Name:         "Single-arm incline rear delt raise",
			Type:         "strength",
			Muscle:       "shoulders",
			Equipment:    "dumbbell",
			Difficulty:   "intermediate",
			Instructions: "While holding a dumbbell in one hand, lay with your chest down on a slightly inclined (around 15 degrees when measured from the floor) adjustable bench. The other hand can be used to hold to the leg of the bench for stability. Position the palm of the hand that is holding the dumbbell in a neutral manner (palms facing your torso) as you keep the arm extended with the elbow slightly bent. This will be your starting position. Now raise the arm with the dumbbell to the side until your elbow is at shoulder height and your arm is roughly parallel to the floor as you exhale. Tip: Maintain your arm perpendicular to the torso while keeping your arm extended throughout the movement. Also, keep the contraction at the top for a second. Slowly lower the dumbbell to the starting position as you inhale. Repeat for the recommended amount of repetitions.  Variations: You can perform this exercise with both arms at the same time and also keeping the palms of the hands facing back as opposed to facing your torso.",
			Image:        "delt-raise.svg",
		},
		
	}

	for _, exercise := range exercises {
		if err := db.Create(&exercise).Error; err != nil {
			logrus.Errorf("Failed to add exercise data: %v", err)
		} else {
			logrus.Infof("Exercise added: %s", exercise.Name)
		}
	}
}
