package datadumy

import (
	"api-peak-form/domain"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

func AddExercise(db *gorm.DB) {
	// Data dummy untuk tabel Exercise
	exercises := []domain.Exercise{
		{
			ID: 125,
			Name: "Pushups",
			Type: "strength",
			Muscle: "chest",
			Equipment: "body_only",
			Difficulty: "intermediate",
			Instructions: "Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length. Next, lower yourself downward until your chest almost touches the floor as you inhale. Now breathe out and press your upper body back up to the starting position while squeezing your chest. After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed. Variations: If you are new at this exercise and do not have the strength to perform it, you can either bend your legs at the knees to take off resistance or perform the exercise against the wall instead of the floor. For the most advanced lifters, you can place your feet at a high surface such as a bench in order to increase the resistance and to target the upper chest more.",
			Image: "pushup.svg",
		},
		{
			ID: 126,
			Name: "Palms-Up Dumbbell Wrist Curl Over A Bench",
			Type: "strength",
			Muscle: "forearms",
			Equipment: "dumbbell",
			Difficulty: "beginner",
			Instructions: "Start out by placing two dumbbells on one side of a flat bench. Kneel down on both of your knees so that your body is facing the flat bench. Use your arms to grab both of the dumbbells with a supinated grip (palms up) and bring them up so that your forearms are resting against the flat bench. Your wrists should be hanging over the edge. Start out by curling your wrist upwards and exhaling. Slowly lower your wrists back down to the starting position while inhaling. Make sure to inhale during this part of the exercise. Your forearms should be stationary as your wrist is the only movement needed to perform this exercise.",
			Image: "wristcurlup.svg",
		},
		{
			ID: 127,
			Name: "Palms-Down Dumbbell Wrist Curl Over A Bench",
			Type: "strength",
			Muscle: "forearms",
			Equipment: "dumbbell",
			Difficulty: "beginner",
			Instructions: "Start out by placing two dumbbells on one side of a flat bench. Kneel down on both of your knees so that your body is facing the flat bench. Use your arms to grab both of the dumbbells with a pronated grip (palms facing down) and bring them up so that your forearms are resting against the flat bench. Your wrists should be hanging over the edge. Start out by curling your wrist upwards and exhaling. Slowly lower your wrists back down to the starting position while inhaling.",
			Image: "wristcurldown.svg",
		},
		{
			ID: 128,
			Name: "Dumbbell Suitcase Carry",
			Type: "strength",
			Muscle: "forearms",
			Equipment: "dumbbell",
			Difficulty: "intermediate",
			Instructions: "Place a dumbbell on the floor in front of you, making sure you have enough open space to walk. Squat down keeping your back flat and grasp the weight with a neutral grip. Keep your body square as much as possible. Stand back up by extending at the hips and knees; this will be your starting position. Keeping the weight at your side, walk forward as far as you can. Descend into a squat to lower the weight back to the floor.",
			Image: "suitcasecarry.svg",
		},
		{
			ID: 129,
			Name: "Pull-up",
			Type: "strength",
			Muscle: "lats",
			Equipment: "body_only",
			Difficulty: "beginner",
			Instructions: "Take a wide grip on a pull-up bar, hanging freely with your arms extended. This will be your starting position. Pull yourself up by flexing the elbows and adducting the glenohumeral joint. Attempt to get your chin above your hands. Pause at the top of the motion before lowering yourself to the starting position.",
			Image: "pullup.svg",
		},
		{
			ID: 130,
			Name: "Wide-Grip Rear Pull-Up",
			Type: "strength",
			Muscle: "lats",
			Equipment: "body_only",
			Difficulty: "beginner",
			Instructions: "Grab the pull-up bar with the palms facing forward using a wide grip. Bring your torso forward and head so that there is an imaginary line from the pull-up bar to the back of your neck. Pull your torso up until the bar is near the back of your neck. Concentrate on squeezing the back muscles once you reach the full contracted position. Slowly lower your torso back to the starting position.",
			Image: "widepullup.svg",
		},
		{
			ID: 131,
			Name: "Muscle Up",
			Type: "strength",
			Muscle: "lats",
			Equipment: "body_only",
			Difficulty: "intermediate",
			Instructions: "Grip the rings using a false grip, with the base of your palms on top of the rings. Initiate a pull up by pulling the elbows down to your side. As you reach the top position of the pull-up, pull the rings to your armpits. This puts you into the proper position to continue into the dip portion of the movement. Maintaining control and stability, extend through the elbow to complete the motion.",
			Image: "muscleup.svg",
		},
		{
			ID: 132,
			Name: "Rope Climb",
			Type: "strength",
			Muscle: "lats",
			Equipment: "body_only",
			Difficulty: "intermediate",
			Instructions: "Grab the rope with both hands above your head. Pull down on the rope as you take a small jump. Wrap the rope around one leg, using your feet to pinch the rope. Reach up as high as possible with your arms, gripping the rope tightly. Release the rope from your feet as you pull yourself up with your arms. Continue until you reach the top of the rope. To lower yourself, loosen the grip of your feet on the rope as you slide down using a hand over hand motion.",
			Image: "ropeclimb.svg",
		},
		{
			ID: 133,
			Name: "Hyperextensions With No Hyperextension Bench",
			Type: "strength",
			Muscle: "lower_back",
			Equipment: "body_only",
			Difficulty: "beginner",
			Instructions: "With someone holding down your legs, slide yourself down to the edge of a flat bench until your hips hang off the end of the bench. Tip: Your entire upper body should be hanging down towards the floor. Also, you will be in the same position as if you were on a hyperextension bench but the range of motion will be shorter due to the height of the flat bench vs. that of the hyperextension bench. With your body straight, cross your arms in front of you (my preference) or behind your head. This will be your starting position. Tip: You can also hold a weight plate for extra resistance in front of you under your crossed arms. Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you almost touch the floor or you feel a nice stretch on the hamstrings (whichever comes first). Tip: Never round the back as you perform this exercise. Slowly raise your torso back to the initial position as you exhale. Tip: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury. Repeat for the recommended amount of repetitions. Variations: This exercise can also be performed using a hyperextension bench. Also, a similar exercise to this one is the good morning and the stiff-legged deadlift.",
			Image: "lowerbackhyperextension.svg",
		},
		{
			ID: 134,
			Name: "Dumbbell Fix Dumbbell Deadlift",
			Type: "strength",
			Muscle: "lower_back",
			Equipment: "dumbbell",
			Difficulty: "intermediate",
			Instructions: "",
			Image: "deadlift.svg",
		},
		{
			ID: 135,
			Name: "Back extension",
			Type: "strength",
			Muscle: "lower_back",
			Equipment: "body_only",
			Difficulty: "intermediate",
			Instructions: "Lie face down on a hyperextension bench, tucking your ankles securely under the footpads. Adjust the upper pad if possible so your upper thighs lie flat across the wide pad, leaving enough room for you to bend at the waist without any restriction. With your body straight, cross your arms in front of you (my preference) or behind your head. This will be your starting position. Tip: You can also hold a weight plate for extra resistance in front of you under your crossed arms. Start bending forward slowly at the waist as far as you can while keeping your back flat. Inhale as you perform this movement. Keep moving forward until you feel a nice stretch on the hamstrings and you can no longer keep going without a rounding of the back. Tip: Never round the back as you perform this exercise. Also, some people can go farther than others. The key thing is that you go as far as your body allows you to without rounding the back. Slowly raise your torso back to the initial position as you inhale. Tip: Avoid the temptation to arch your back past a straight line. Also, do not swing the torso at any time in order to protect the back from injury. Repeat for the recommended amount of repetitions. Variations: This exercise can also be performed without a hyperextension bench, but in this case, you will need a spotter. Also, a similar exercise to this one is the good morning and the stiff-legged deadlift.",
			Image: "backextension.svg",
		},
		{
			ID: 136,
			Name: "Bent Over Two-Dumbbell Row With Palms In",
			Type: "strength",
			Muscle: "middle_back",
			Equipment: "dumbbell",
			Difficulty: "beginner",
			Instructions: "With a dumbbell in each hand (palms facing each other), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The weights should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position. While keeping the torso stationary, lift the dumbbells to your side as you breathe out, squeezing your shoulder blades together. On the top contracted position, squeeze the back muscles and hold for a second. Slowly lower the weight again to the starting position as you inhale. Repeat for the recommended amount of repetitions.",
			Image: "bentoverrow.svg",
		},
		{
			ID: 137,
			Name: "One-Arm Dumbbell Row",
			Type: "strength",
			Muscle: "middle_back",
			Equipment: "dumbbell",
			Difficulty: "intermediate",
			Instructions: "Choose a flat bench and place a dumbbell on each side of it. Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support. Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position. Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step.",
			Image: "dumbellrow.svg",
		},
		{
			ID: 138,
			Name: "Isometric Neck Exercise - Sides",
			Type: "strength",
			Muscle: "neck",
			Equipment: "body_only",
			Difficulty: "beginner",
			Instructions: "With your head and neck in a neutral position (normal position with head erect facing forward), place your left hand on the left side of your head. Now gently push towards the left as you contract the left neck muscles but resisting any movement of your head. Start with slow tension and increase slowly. Keep breathing normally as you execute this contraction. Hold for the recommended number of seconds.",
			Image: "necksides.svg",
		},
		{
			ID: 139,
			Name: "Dumbbell Goblet Squat",
			Type: "strength",
			Muscle: "quadriceps",
			Equipment: "dumbbell",
			Difficulty: "intermediate",
			Instructions: "From a standing position cradle the head of a dumbbell close to your chest with both hands. You should be looking straight forward, with your shoulders back, your spine straight, and your feet just outside of shoulder width. This will be your starting position. Initiate the movement by descending into a squat, flexing the hips and knees to lower your body.",
			Image: "gobletsquat.svg",
		},
		{
			ID: 140,
			Name: "Dumbbell squat",
			Type: "strength",
			Muscle: "quadriceps",
			Equipment: "dumbbell",
			Difficulty: "intermediate",
			Instructions: "Stand up straight while holding a dumbbell on each hand (palms facing the side of your legs). Position your legs using a shoulder-width medium stance with the toes slightly pointed out. Keep your head up at all times.",
			Image: "dumbellsquat.svg",
		},
		{
			ID: 141,
			Name: "Forward lunge",
			Type: "strength",
			Muscle: "quadriceps",
			Equipment: "body_only",
			Difficulty: "intermediate",
			Instructions: "Stand erect with your feet hip-width apart, chest out, and shoulders back, maintaining the natural curvature of your spine. Your knees should be unlocked and your hand on your hips. This is your starting position.",
			Image: "lunge.svg",
		},

		{
			ID: 142,
			Name: "Standing dumbbell shrug",
			Type: "strength",
			Muscle: "traps",
			Equipment: "dumbbell",
			Difficulty: "intermediate",
			Instructions: "Stand erect with a dumbbell on each hand (palms facing your torso), arms extended on the sides. Lift the dumbbells by elevating the shoulders as high as possible while you exhale. Hold the contraction at the top for a second. Tip: The arms should remain extended at all times. Refrain from using the biceps to help lift the dumbbells. Only the shoulders should be moving up and down. Lower the dumbbells back to the original position. Repeat for the recommended amount of repetitions. Variations: You can perform this exercise with bands, barbells or cables. You can also use a single handle and work one side at a time.",
			Image: "shrug.svg",
		},
		{
			ID: 143,
			Name: "Standing dumbbell upright row",
			Type: "strength",
			Muscle: "traps",
			Equipment: "dumbbell",
			Difficulty: "intermediate",
			Instructions: "Grasp a dumbbell in each hand with a pronated (palms forward) grip that is slightly less than shoulder width. The dumbbells should be resting on top of your thighs. Your arms should be extended with a slight bend at the elbows and your back should be straight. This will be your starting position. Use your side shoulders to lift the dumbbells as you exhale. The dumbbells should be close to the body as you move it up and the elbows should drive the motion. Continue to lift them until they nearly touch your chin. Tip: Your elbows should drive the motion. As you lift the dumbbells, your elbows should always be higher than your forearms. Also, keep your torso stationary and pause for a second at the top of the movement. Lower the dumbbells back down slowly to the starting position. Inhale as you perform this portion of the movement. Repeat for the recommended amount of repetitions. Caution: Be very careful with how much weight you use in this exercise. Too much weight leads to bad form, which in turn can cause shoulder injury. I've seen this too many times so please no jerking, swinging and cheating. Also, if you suffer from shoulder problems, you may want to stay away from upright rows and substitute by some form of lateral raises. Variations: This exercise can also be performed using a straight bar attached to a low pulley and it can also be performed using an e-z bar.",
			Image: "uprightrow.svg",
		},
		{
			ID: 144,
			Name: "One Arm Supinated Dumbbell Triceps Extension",
			Type: "strength",
			Muscle: "triceps",
			Equipment: "dumbbell",
			Difficulty: "beginner",
			Instructions: "Lie flat on a bench while holding a dumbbell at arms length. Your arm should be perpendicular to your body. The palm of your hand should be facing towards your face as a supinated grip is required to perform this exercise. Place your non lifting hand on your bicep for support. Slowly begin to lower the dumbbell down as you breathe in. Then, begin lifting the dumbbell upward as you contract the triceps. Remember to breathe out during the concentric (lifting part of the exercise). Repeat until you have performed your set repetitions. Switch arms and repeat the movement. Switch arms again and repeat the movement. Caution: When you are done, do not drop the dumbbell next to you as this is dangerous to your rotator cuff in your shoulders and others working out around you. Just lift your legs from the floor bending at the knees, twist your wrist so that you can place the dumbbell on top of your thigh. When the dumbbell is touching your thigh simultaneously push your upper torso up (while pressing the dumbbell on your thigh) and also perform a slight kick forward with your legs (keeping the dumbbell on top of the thigh). By doing this combined movement, momentum will help you get back to a sitting position with the dumbbell still on top of your thigh. At this moment you can place the dumbbell on the floor.",
			Image: "tricepsextension.svg",
		},
		{
			ID: 145,
			Name: "Seated Bent-Over Two-Arm Dumbbell Triceps Extension",
			Type: "strength",
			Muscle: "triceps",
			Equipment: "dumbbell",
			Difficulty: "beginner",
			Instructions: "Sit down at the end of a flat bench with a dumbbell in both arms using a neutral grip (palms of the hand facing you). Bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Make sure that you keep the head up. The upper arms with the dumbbells should be close to the torso and aligned with it (lifted up until they are parallel to the floor while the forearms are pointing towards the floor as the hands hold the weights). Tip: There should be a 90-degree angle between the forearms and the upper arm. This is your starting position. Keeping the upper arms stationary, use the triceps to lift the weight as you exhale until the forearms are parallel to the floor and the whole arm is extended. Like many other arm exercises, only the forearm moves. After a second contraction at the top, slowly lower the dumbbells back to the starting position as you inhale. Repeat the movement for the prescribed amount of repetitions. Variation: This exercise can be executed also one arm at a time or alternating (like alternating dumbbell curls)",
			Image: "dumbellrowtricep.svg",
		},
		{
			ID: 146,
			Name: "Triceps dip",
			Type: "strength",
			Muscle: "triceps",
			Equipment: "body_only",
			Difficulty: "intermediate",
			Instructions: "To get into the starting position, hold your body at arm's length with your arms nearly locked above the bars. Now, inhale and slowly lower yourself downward. Your torso should remain upright and your elbows should stay close to your body. This helps to better focus on tricep involvement. Lower yourself until there is a 90 degree angle formed between the upper arm and forearm. Then, exhale and push your torso back up using your triceps to bring your body back to the starting position. Repeat the movement for the prescribed amount of repetitions. Variations: If you are new at this exercise and do not have the strength to perform it, use a dip assist machine if available. These machines use weight to help you push your bodyweight. Otherwise, a spotter holding your legs can help. More advanced lifters can add weight to the exercise by using a weight belt that allows the addition of weighted plates.",
			Image: "dip.svg",
		},
		{
			ID: 147,
			Name: "Push-Ups - Close Triceps Position",
			Type: "strength",
			Muscle: "triceps",
			Equipment: "body_only",
			Difficulty: "intermediate",
			Instructions: "Lie on the floor face down and place your hands closer than shoulder width for a close hand position. Make sure that you are holding your torso up at arms' length. Lower yourself until your chest almost touches the floor as you inhale. Using your triceps and some of your pectoral muscles, press your upper body back up to the starting position and squeeze your chest. Breathe out as you perform this step. After a second pause at the contracted position, repeat the movement for the prescribed amount of repetitions. Variations: If you are new at this exercise and do not have the strength to perform it, you can either bend your legs at the knees to take off resistance or perform the exercise against the wall instead of the floor. For the most advanced lifters, you can place your feet at a high surface such as a bench in order to increase the resistance.",
			Image: "closepushup.svg",
		},
	}

	for _, exercise := range exercises {
		if err := db.Create(&exercise).Error; err != nil {
			logrus.Errorf("Failed to add exercise data: %v", err)
		} else {
			logrus.Infof("Exercise added: %s", exercise.Name)
		}
	}
}
